### ISSUE TITLE
No function named "TIM_decomposition"?

### ISSUE THREAD

**Issue by ctfysh** [MichalisHadjikakou/Scarcity-water-footprints-#1]
Hi. When I read the file "Master_script_AUS_Scarcity_Water_Footprints_16_March_2018.m", I find that 3 
 functions are used: `AUS_RoW_disaggregation`, `Calculate_multipliers_modified`, `TIM_decomposition`. However, I cannot find the function code named "TIM_decomposition.m".

**Comment by MichalisHadjikakou** [comment]
Hi, thanks for the comment; I must have forgotten to upload it. Will create another release and include the file. In the meantime, here is the function. 
[TIM_decomposition.zip](https://github.com/MichalisHadjikakou/Scarcity-water-footprints-/files/2140022/TIM_decomposition.zip)

I hope you're finding the code useful for your purposes. Let me know if anything else is missing. 

Kind regards,

Michalis
